FROM ufoym/deepo:all-jupyter-py36-cu90

RUN pip3 install tqdm==4.28.1
RUN pip3 install torch==1.0.1.post2
RUN pip3 install fasttext==0.8.3
RUN pip3 install lightgbm==2.2.3
RUN pip3 install lightfm==1.15
